### ISSUE TITLE
Read only rating bar

### ISSUE THREAD

**Issue by abdulwahid24** [joshmatta/rating_bar#1]
I appriciate the rating bar implementation. 
I think there should also be a privilege of having read-only rating bar.

**Comment by jajpa** [comment]
Would add this feature. But for now you can wrap the widget with AbsorbPointer widget to make it read only

**Comment by jajpa** [comment]
This feature has been added in the new version. Please check README.

**Comment by abdulwahid24** [comment]
Great, Really appreciated. Thank you.
